project_name: aikor-nginx
env:
  - GO111MODULE=on
builds:
  - binary: aikor-nginx
    ldflags:
      - -s -w
      - -X main.NginxBuildVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - s390x
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-v{{ .Version }}'
release:
  prerelease: auto
