language: go
go:
  - 1.5.4
  - 1.6.2
  - tip
before_install:
  - go get github.com/Masterminds/glide
script:
  - sudo apt-get install -y libgd2-xpm-dev
  - make bundle
  - make
  - make check
  - ./nginx-build -c ./config/configure.example -m ./config/modules.cfg.example -d work -clear -pcre -zlib -openssl
