name: Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Nginx
        run: bash <(curl -Ls https://raw.githubusercontent.com/AikoCute-Offical/AikoR-Nginx/master/build/aiko.sh)