name: Test

on: [push]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x

    - name: Build
      run: make

    - name: Test
      run: make check

    - name: Run
      run: |
        make
        ./aikor-nginx -c ./config/configure.example -m ./config/modules.json.example -d work -clear -zlib -openssl
